---
#
# Template sensor to display the thermostat cooling current temp
#
# https://www.home-assistant.io/components/sensor.template/
# 
platform: template
sensors:
  thermostat_cool_current_temperature:
    friendly_name: "Thermostat Cool Current Temperature"
    device_class: "temperature"
    unit_of_measurement: "Â°F"
    value_template: >-
      {%- if state_attr('climate.2gig_technologies_ct101_thermostat_iris_cooling_1', 'current_temperature') %}
          {{ state_attr('climate.2gig_technologies_ct101_thermostat_iris_cooling_1', 'current_temperature') }}
      {% else %}
          Unknown
      {%- endif %}